In [2]:
import pandas as pd

In [3]:
years = [1820, 1830, 1840, 1850, 1860, 1870, 1880, 1890, 1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000]
verbs = ['bear', 'bring', 'create', 'give', 'grant', 'hold', 'keep', 'lose', 'make', 'take','maintain', 'demand']
genres = ['NF', 'FIC', 'MAG']

In [9]:
for v in verbs:
    for y in years:
        for g in genres:
            print(v + ' '+ str(y)+'algo' + ' '+ g)

bear 1820algo NF
bear 1820algo FIC
bear 1820algo MAG
bear 1830algo NF
bear 1830algo FIC
bear 1830algo MAG
bear 1840algo NF
bear 1840algo FIC
bear 1840algo MAG
bear 1850algo NF
bear 1850algo FIC
bear 1850algo MAG
bear 1860algo NF
bear 1860algo FIC
bear 1860algo MAG
bear 1870algo NF
bear 1870algo FIC
bear 1870algo MAG
bear 1880algo NF
bear 1880algo FIC
bear 1880algo MAG
bear 1890algo NF
bear 1890algo FIC
bear 1890algo MAG
bear 1900algo NF
bear 1900algo FIC
bear 1900algo MAG
bear 1910algo NF
bear 1910algo FIC
bear 1910algo MAG
bear 1920algo NF
bear 1920algo FIC
bear 1920algo MAG
bear 1930algo NF
bear 1930algo FIC
bear 1930algo MAG
bear 1940algo NF
bear 1940algo FIC
bear 1940algo MAG
bear 1950algo NF
bear 1950algo FIC
bear 1950algo MAG
bear 1960algo NF
bear 1960algo FIC
bear 1960algo MAG
bear 1970algo NF
bear 1970algo FIC
bear 1970algo MAG
bear 1980algo NF
bear 1980algo FIC
bear 1980algo MAG
bear 1990algo NF
bear 1990algo FIC
bear 1990algo MAG
bear 2000algo NF
bear 2000algo FIC
bear 2000algo MAG
bring 1820algo NF
bring 1820algo FIC
bring 1820algo MAG
bring 1830algo NF
bring 1830algo FIC
bring 1830algo MAG
bring 1840algo NF
bring 1840algo FIC
bring 1840algo MAG
bring 1850algo NF
bring 1850algo FIC
bring 1850algo MAG
bring 1860algo NF
bring 1860algo FIC
bring 1860algo MAG
bring 1870algo NF
bring 1870algo FIC
bring 1870algo MAG
bring 1880algo NF
bring 1880algo FIC
bring 1880algo MAG
bring 1890algo NF
bring 1890algo FIC
bring 1890algo MAG
bring 1900algo NF
bring 1900algo FIC
bring 1900algo MAG
bring 1910algo NF
bring 1910algo FIC
bring 1910algo MAG
bring 1920algo NF
bring 1920algo FIC
bring 1920algo MAG
bring 1930algo NF
bring 1930algo FIC
bring 1930algo MAG
bring 1940algo NF
bring 1940algo FIC
bring 1940algo MAG
bring 1950algo NF
bring 1950algo FIC
bring 1950algo MAG
bring 1960algo NF
bring 1960algo FIC
bring 1960algo MAG
bring 1970algo NF
bring 1970algo FIC
bring 1970algo MAG
bring 1980algo NF
bring 1980algo FIC
bring 1980algo MAG
bring 1990algo NF
bring 1990algo FIC
bring 1990algo MAG
bring 2000algo NF
bring 2000algo FIC
bring 2000algo MAG
create 1820algo NF
create 1820algo FIC
create 1820algo MAG
create 1830algo NF
create 1830algo FIC
create 1830algo MAG
create 1840algo NF
create 1840algo FIC
create 1840algo MAG
create 1850algo NF
create 1850algo FIC
create 1850algo MAG
create 1860algo NF
create 1860algo FIC
create 1860algo MAG
create 1870algo NF
create 1870algo FIC
create 1870algo MAG
create 1880algo NF
create 1880algo FIC
create 1880algo MAG
create 1890algo NF
create 1890algo FIC
create 1890algo MAG
create 1900algo NF
create 1900algo FIC
create 1900algo MAG
create 1910algo NF
create 1910algo FIC
create 1910algo MAG
create 1920algo NF
create 1920algo FIC
create 1920algo MAG
create 1930algo NF
create 1930algo FIC
create 1930algo MAG
create 1940algo NF
create 1940algo FIC
create 1940algo MAG
create 1950algo NF
create 1950algo FIC
create 1950algo MAG
create 1960algo NF
create 1960algo FIC
create 1960algo MAG
create 1970algo NF
create 1970algo FIC
create 1970algo MAG
create 1980algo NF
create 1980algo FIC
create 1980algo MAG
create 1990algo NF
create 1990algo FIC
create 1990algo MAG
create 2000algo NF
create 2000algo FIC
create 2000algo MAG
give 1820algo NF
give 1820algo FIC
give 1820algo MAG
give 1830algo NF
give 1830algo FIC
give 1830algo MAG
give 1840algo NF
give 1840algo FIC
give 1840algo MAG
give 1850algo NF
give 1850algo FIC
give 1850algo MAG
give 1860algo NF
give 1860algo FIC
give 1860algo MAG
give 1870algo NF
give 1870algo FIC
give 1870algo MAG
give 1880algo NF
give 1880algo FIC
give 1880algo MAG
give 1890algo NF
give 1890algo FIC
give 1890algo MAG
give 1900algo NF
give 1900algo FIC
give 1900algo MAG
give 1910algo NF
give 1910algo FIC
give 1910algo MAG
give 1920algo NF
give 1920algo FIC
give 1920algo MAG
give 1930algo NF
give 1930algo FIC
give 1930algo MAG
give 1940algo NF
give 1940algo FIC
give 1940algo MAG
give 1950algo NF
give 1950algo FIC
give 1950algo MAG
give 1960algo NF
give 1960algo FIC
give 1960algo MAG
give 1970algo NF
give 1970algo FIC
give 1970algo MAG
give 1980algo NF
give 1980algo FIC
give 1980algo MAG
give 1990algo NF
give 1990algo FIC
give 1990algo MAG
give 2000algo NF
give 2000algo FIC
give 2000algo MAG
grant 1820algo NF
grant 1820algo FIC
grant 1820algo MAG
grant 1830algo NF
grant 1830algo FIC
grant 1830algo MAG
grant 1840algo NF
grant 1840algo FIC
grant 1840algo MAG
grant 1850algo NF
grant 1850algo FIC
grant 1850algo MAG
grant 1860algo NF
grant 1860algo FIC
grant 1860algo MAG
grant 1870algo NF
grant 1870algo FIC
grant 1870algo MAG
grant 1880algo NF
grant 1880algo FIC
grant 1880algo MAG
grant 1890algo NF
grant 1890algo FIC
grant 1890algo MAG
grant 1900algo NF
grant 1900algo FIC
grant 1900algo MAG
grant 1910algo NF
grant 1910algo FIC
grant 1910algo MAG
grant 1920algo NF
grant 1920algo FIC
grant 1920algo MAG
grant 1930algo NF
grant 1930algo FIC
grant 1930algo MAG
grant 1940algo NF
grant 1940algo FIC
grant 1940algo MAG
grant 1950algo NF
grant 1950algo FIC
grant 1950algo MAG
grant 1960algo NF
grant 1960algo FIC
grant 1960algo MAG
grant 1970algo NF
grant 1970algo FIC
grant 1970algo MAG
grant 1980algo NF
grant 1980algo FIC
grant 1980algo MAG
grant 1990algo NF
grant 1990algo FIC
grant 1990algo MAG
grant 2000algo NF
grant 2000algo FIC
grant 2000algo MAG
hold 1820algo NF
hold 1820algo FIC
hold 1820algo MAG
hold 1830algo NF
hold 1830algo FIC
hold 1830algo MAG
hold 1840algo NF
hold 1840algo FIC
hold 1840algo MAG
hold 1850algo NF
hold 1850algo FIC
hold 1850algo MAG
hold 1860algo NF
hold 1860algo FIC
hold 1860algo MAG
hold 1870algo NF
hold 1870algo FIC
hold 1870algo MAG
hold 1880algo NF
hold 1880algo FIC
hold 1880algo MAG
hold 1890algo NF
hold 1890algo FIC
hold 1890algo MAG
hold 1900algo NF
hold 1900algo FIC
hold 1900algo MAG
hold 1910algo NF
hold 1910algo FIC
hold 1910algo MAG
hold 1920algo NF
hold 1920algo FIC
hold 1920algo MAG
hold 1930algo NF
hold 1930algo FIC
hold 1930algo MAG
hold 1940algo NF
hold 1940algo FIC
hold 1940algo MAG
hold 1950algo NF
hold 1950algo FIC
hold 1950algo MAG
hold 1960algo NF
hold 1960algo FIC
hold 1960algo MAG
hold 1970algo NF
hold 1970algo FIC
hold 1970algo MAG
hold 1980algo NF
hold 1980algo FIC
hold 1980algo MAG
hold 1990algo NF
hold 1990algo FIC
hold 1990algo MAG
hold 2000algo NF
hold 2000algo FIC
hold 2000algo MAG
keep 1820algo NF
keep 1820algo FIC
keep 1820algo MAG
keep 1830algo NF
keep 1830algo FIC
keep 1830algo MAG
keep 1840algo NF
keep 1840algo FIC
keep 1840algo MAG
keep 1850algo NF
keep 1850algo FIC
keep 1850algo MAG
keep 1860algo NF
keep 1860algo FIC
keep 1860algo MAG
keep 1870algo NF
keep 1870algo FIC
keep 1870algo MAG
keep 1880algo NF
keep 1880algo FIC
keep 1880algo MAG
keep 1890algo NF
keep 1890algo FIC
keep 1890algo MAG
keep 1900algo NF
keep 1900algo FIC
keep 1900algo MAG
keep 1910algo NF
keep 1910algo FIC
keep 1910algo MAG
keep 1920algo NF
keep 1920algo FIC
keep 1920algo MAG
keep 1930algo NF
keep 1930algo FIC
keep 1930algo MAG
keep 1940algo NF
keep 1940algo FIC
keep 1940algo MAG
keep 1950algo NF
keep 1950algo FIC
keep 1950algo MAG
keep 1960algo NF
keep 1960algo FIC
keep 1960algo MAG
keep 1970algo NF
keep 1970algo FIC
keep 1970algo MAG
keep 1980algo NF
keep 1980algo FIC
keep 1980algo MAG
keep 1990algo NF
keep 1990algo FIC
keep 1990algo MAG
keep 2000algo NF
keep 2000algo FIC
keep 2000algo MAG
lose 1820algo NF
lose 1820algo FIC
lose 1820algo MAG
lose 1830algo NF
lose 1830algo FIC
lose 1830algo MAG
lose 1840algo NF
lose 1840algo FIC
lose 1840algo MAG
lose 1850algo NF
lose 1850algo FIC
lose 1850algo MAG
lose 1860algo NF
lose 1860algo FIC
lose 1860algo MAG
lose 1870algo NF
lose 1870algo FIC
lose 1870algo MAG
lose 1880algo NF
lose 1880algo FIC
lose 1880algo MAG
lose 1890algo NF
lose 1890algo FIC
lose 1890algo MAG
lose 1900algo NF
lose 1900algo FIC
lose 1900algo MAG
lose 1910algo NF
lose 1910algo FIC
lose 1910algo MAG
lose 1920algo NF
lose 1920algo FIC
lose 1920algo MAG
lose 1930algo NF
lose 1930algo FIC
lose 1930algo MAG
lose 1940algo NF
lose 1940algo FIC
lose 1940algo MAG
lose 1950algo NF
lose 1950algo FIC
lose 1950algo MAG
lose 1960algo NF
lose 1960algo FIC
lose 1960algo MAG
lose 1970algo NF
lose 1970algo FIC
lose 1970algo MAG
lose 1980algo NF
lose 1980algo FIC
lose 1980algo MAG
lose 1990algo NF
lose 1990algo FIC
lose 1990algo MAG
lose 2000algo NF
lose 2000algo FIC
lose 2000algo MAG
make 1820algo NF
make 1820algo FIC
make 1820algo MAG
make 1830algo NF
make 1830algo FIC
make 1830algo MAG
make 1840algo NF
make 1840algo FIC
make 1840algo MAG
make 1850algo NF
make 1850algo FIC
make 1850algo MAG
make 1860algo NF
make 1860algo FIC
make 1860algo MAG
make 1870algo NF
make 1870algo FIC
make 1870algo MAG
make 1880algo NF
make 1880algo FIC
make 1880algo MAG
make 1890algo NF
make 1890algo FIC
make 1890algo MAG
make 1900algo NF
make 1900algo FIC
make 1900algo MAG
make 1910algo NF
make 1910algo FIC
make 1910algo MAG
make 1920algo NF
make 1920algo FIC
make 1920algo MAG
make 1930algo NF
make 1930algo FIC
make 1930algo MAG
make 1940algo NF
make 1940algo FIC
make 1940algo MAG
make 1950algo NF
make 1950algo FIC
make 1950algo MAG
make 1960algo NF
make 1960algo FIC
make 1960algo MAG
make 1970algo NF
make 1970algo FIC
make 1970algo MAG
make 1980algo NF
make 1980algo FIC
make 1980algo MAG
make 1990algo NF
make 1990algo FIC
make 1990algo MAG
make 2000algo NF
make 2000algo FIC
make 2000algo MAG
take 1820algo NF
take 1820algo FIC
take 1820algo MAG
take 1830algo NF
take 1830algo FIC
take 1830algo MAG
take 1840algo NF
take 1840algo FIC
take 1840algo MAG
take 1850algo NF
take 1850algo FIC
take 1850algo MAG
take 1860algo NF
take 1860algo FIC
take 1860algo MAG
take 1870algo NF
take 1870algo FIC
take 1870algo MAG
take 1880algo NF
take 1880algo FIC
take 1880algo MAG
take 1890algo NF
take 1890algo FIC
take 1890algo MAG
take 1900algo NF
take 1900algo FIC
take 1900algo MAG
take 1910algo NF
take 1910algo FIC
take 1910algo MAG
take 1920algo NF
take 1920algo FIC
take 1920algo MAG
take 1930algo NF
take 1930algo FIC
take 1930algo MAG
take 1940algo NF
take 1940algo FIC
take 1940algo MAG
take 1950algo NF
take 1950algo FIC
take 1950algo MAG
take 1960algo NF
take 1960algo FIC
take 1960algo MAG
take 1970algo NF
take 1970algo FIC
take 1970algo MAG
take 1980algo NF
take 1980algo FIC
take 1980algo MAG
take 1990algo NF
take 1990algo FIC
take 1990algo MAG
take 2000algo NF
take 2000algo FIC
take 2000algo MAG
maintain 1820algo NF
maintain 1820algo FIC
maintain 1820algo MAG
maintain 1830algo NF
maintain 1830algo FIC
maintain 1830algo MAG
maintain 1840algo NF
maintain 1840algo FIC
maintain 1840algo MAG
maintain 1850algo NF
maintain 1850algo FIC
maintain 1850algo MAG
maintain 1860algo NF
maintain 1860algo FIC
maintain 1860algo MAG
maintain 1870algo NF
maintain 1870algo FIC
maintain 1870algo MAG
maintain 1880algo NF
maintain 1880algo FIC
maintain 1880algo MAG
maintain 1890algo NF
maintain 1890algo FIC
maintain 1890algo MAG
maintain 1900algo NF
maintain 1900algo FIC
maintain 1900algo MAG
maintain 1910algo NF
maintain 1910algo FIC
maintain 1910algo MAG
maintain 1920algo NF
maintain 1920algo FIC
maintain 1920algo MAG
maintain 1930algo NF
maintain 1930algo FIC
maintain 1930algo MAG
maintain 1940algo NF
maintain 1940algo FIC
maintain 1940algo MAG
maintain 1950algo NF
maintain 1950algo FIC
maintain 1950algo MAG
maintain 1960algo NF
maintain 1960algo FIC
maintain 1960algo MAG
maintain 1970algo NF
maintain 1970algo FIC
maintain 1970algo MAG
maintain 1980algo NF
maintain 1980algo FIC
maintain 1980algo MAG
maintain 1990algo NF
maintain 1990algo FIC
maintain 1990algo MAG
maintain 2000algo NF
maintain 2000algo FIC
maintain 2000algo MAG
demand 1820algo NF
demand 1820algo FIC
demand 1820algo MAG
demand 1830algo NF
demand 1830algo FIC
demand 1830algo MAG
demand 1840algo NF
demand 1840algo FIC
demand 1840algo MAG
demand 1850algo NF
demand 1850algo FIC
demand 1850algo MAG
demand 1860algo NF
demand 1860algo FIC
demand 1860algo MAG
demand 1870algo NF
demand 1870algo FIC
demand 1870algo MAG
demand 1880algo NF
demand 1880algo FIC
demand 1880algo MAG
demand 1890algo NF
demand 1890algo FIC
demand 1890algo MAG
demand 1900algo NF
demand 1900algo FIC
demand 1900algo MAG
demand 1910algo NF
demand 1910algo FIC
demand 1910algo MAG
demand 1920algo NF
demand 1920algo FIC
demand 1920algo MAG
demand 1930algo NF
demand 1930algo FIC
demand 1930algo MAG
demand 1940algo NF
demand 1940algo FIC
demand 1940algo MAG
demand 1950algo NF
demand 1950algo FIC
demand 1950algo MAG
demand 1960algo NF
demand 1960algo FIC
demand 1960algo MAG
demand 1970algo NF
demand 1970algo FIC
demand 1970algo MAG
demand 1980algo NF
demand 1980algo FIC
demand 1980algo MAG
demand 1990algo NF
demand 1990algo FIC
demand 1990algo MAG
demand 2000algo NF
demand 2000algo FIC
demand 2000algo MAG

In [15]:
f = open("algoQueryPartitionsByGenre.sql", "a+")
for v in verbs:
    for y in years:
        for g in genres:
#             print(v + ' '+ str(y)+'algo' + ' '+ g)
            sqlQuery = """
COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM """ + 'p' + str(y) + "algo" + """ as c, lexicon as l, sources as s
where l.lemma like '""" + v + """'
and c.w1 = l.wid and s.textid = c.source and s.genre = '""" + g + """'
UNION ALL
SELECT c.w3 FROM """ + 'p' + str(y) + "algo" +""" as c, lexicon as l, sources as s
where l.lemma like '""" + v + """'
and c.w1 = l.wid and s.textid = c.source and s.genre = '""" + g + """'
UNION ALL
SELECT c.w4 FROM """ + 'p' + str(y) + "algo"+""" as c, lexicon as l, sources as s
where l.lemma like '""" + v + """'
and c.w1 = l.wid and s.textid = c.source and s.genre = '""" + g + """'
UNION ALL
SELECT c.w5 FROM """ + 'p' + str(y) + "algo"+ """ as c, lexicon as l, sources as s
where l.lemma like '""" + v + """'
and c.w1 = l.wid and s.textid = c.source and s.genre = '""" + g + """'
UNION ALL
SELECT c.w6 FROM """ + 'p' + str(y) + "algo" +""" as c, lexicon as l, sources as s
where l.lemma like '""" + v + """'
and c.w1 = l.wid and s.textid = c.source and s.genre = '""" + g + """'
) a, lexicon b where 
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO """ + "\'/var/lib/postgresql/algoResult/" + v + str(y) + g +".csv\' CSV HEADER;\n"

            print(sqlQuery)
            f.write(sqlQuery)
f.close()

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w3 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w4 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w5 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w6 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1820NF.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w3 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w4 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w5 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w6 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1820FIC.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w3 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w4 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w5 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w6 FROM p1820algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1820MAG.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w3 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w4 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w5 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w6 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1830NF.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w3 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w4 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w5 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w6 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1830FIC.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w3 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w4 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w5 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w6 FROM p1830algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1830MAG.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w3 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w4 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w5 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w6 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1840NF.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w3 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w4 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w5 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w6 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1840FIC.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w3 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w4 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w5 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w6 FROM p1840algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1840MAG.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w3 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w4 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w5 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w6 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1850NF.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w3 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w4 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w5 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w6 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1850FIC.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w3 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w4 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w5 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w6 FROM p1850algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1850MAG.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w3 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w4 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w5 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w6 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1860NF.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w3 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w4 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w5 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w6 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1860FIC.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w3 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w4 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w5 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w6 FROM p1860algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1860MAG.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w3 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w4 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w5 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w6 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1870NF.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w3 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w4 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w5 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
UNION ALL
SELECT c.w6 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'FIC'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1870FIC.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w3 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w4 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w5 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
UNION ALL
SELECT c.w6 FROM p1870algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'MAG'
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1870MAG.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1880algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w3 FROM p1880algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w4 FROM p1880algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w5 FROM p1880algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
UNION ALL
SELECT c.w6 FROM p1880algo as c, lexicon as l, sources as s
where l.lemma like 'bear'
and c.w1 = l.wid and s.textid = c.source and s.genre = 'NF'
) a, lexicon b where