In [2]:
import pandas as pd

In [3]:
years = [1820, 1830, 1840, 1850, 1860, 1870, 1880, 1890, 1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000]
verbs = ['bring', 'hold', 'keep', 'lose']

In [5]:
for v in verbs:
    for y in years:
        print(v + ' '+ str(y))

bring 1820
bring 1830
bring 1840
bring 1850
bring 1860
bring 1870
bring 1880
bring 1890
bring 1900
bring 1910
bring 1920
bring 1930
bring 1940
bring 1950
bring 1960
bring 1970
bring 1980
bring 1990
bring 2000
hold 1820
hold 1830
hold 1840
hold 1850
hold 1860
hold 1870
hold 1880
hold 1890
hold 1900
hold 1910
hold 1920
hold 1930
hold 1940
hold 1950
hold 1960
hold 1970
hold 1980
hold 1990
hold 2000
keep 1820
keep 1830
keep 1840
keep 1850
keep 1860
keep 1870
keep 1880
keep 1890
keep 1900
keep 1910
keep 1920
keep 1930
keep 1940
keep 1950
keep 1960
keep 1970
keep 1980
keep 1990
keep 2000
lose 1820
lose 1830
lose 1840
lose 1850
lose 1860
lose 1870
lose 1880
lose 1890
lose 1900
lose 1910
lose 1920
lose 1930
lose 1940
lose 1950
lose 1960
lose 1970
lose 1980
lose 1990
lose 2000

In [9]:
f = open("queryPartitions.sql", "a+")
for v in verbs:
    for y in years:
        sqlQuery = """
COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM """ + 'p' + str(y) + """ as c, lexicon as l
where l.lemma like '""" + v + """'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM """ + 'p' + str(y) + """ as c, lexicon as l
where l.lemma like '""" + v + """'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM """ + 'p' + str(y) + """ as c, lexicon as l
where l.lemma like '""" + v + """'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM """ + 'p' + str(y) + """ as c, lexicon as l
where l.lemma like '""" + v + """'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM """ + 'p' + str(y) + """ as c, lexicon as l
where l.lemma like '""" + v + """'
and c.w1 = l.wid
) a, lexicon b where 
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc;
) TO """ + "\'/var/lib/postgresql/" + v + str(y) + ".csv\' CSV HEADER;"

        print(sqlQuery)
        f.write(sqlQuery)
f.close()

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1820 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1820 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1820 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1820 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1820 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc;
) TO '/var/lib/postgresql/bring1820.csv' CSV HEADER;

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1830 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1830 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1830 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1830 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1830 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc;
) TO '/var/lib/postgresql/bring1830.csv' CSV HEADER;

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1840 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1840 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1840 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1840 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1840 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc;
) TO '/var/lib/postgresql/bring1840.csv' CSV HEADER;

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1850 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1850 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1850 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1850 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1850 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc;
) TO '/var/lib/postgresql/bring1850.csv' CSV HEADER;

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1860 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1860 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1860 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1860 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1860 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc;
) TO '/var/lib/postgresql/bring1860.csv' CSV HEADER;

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1870 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1870 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1870 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1870 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1870 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc;
) TO '/var/lib/postgresql/bring1870.csv' CSV HEADER;

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1880 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1880 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1880 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1880 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1880 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc;
) TO '/var/lib/postgresql/bring1880.csv' CSV HEADER;

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1890 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1890 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1890 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1890 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1890 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc;
) TO '/var/lib/postgresql/bring1890.csv' CSV HEADER;

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1900 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1900 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1900 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1900 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1900 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc;
) TO '/var/lib/postgresql/bring1900.csv' CSV HEADER;

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1910 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1910 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1910 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1910 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1910 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc;
) TO '/var/lib/postgresql/bring1910.csv' CSV HEADER;

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1920 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1920 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1920 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1920 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1920 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc;
) TO '/var/lib/postgresql/bring1920.csv' CSV HEADER;

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1930 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1930 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1930 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1930 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1930 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc;
) TO '/var/lib/postgresql/bring1930.csv' CSV HEADER;

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1940 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1940 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1940 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1940 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1940 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc;
) TO '/var/lib/postgresql/bring1940.csv' CSV HEADER;

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1950 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1950 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1950 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1950 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1950 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc;
) TO '/var/lib/postgresql/bring1950.csv' CSV HEADER;

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1960 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1960 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1960 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1960 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1960 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc;
) TO '/var/lib/postgresql/bring1960.csv' CSV HEADER;

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1970 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1970 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1970 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1970 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1970 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc;
) TO '/var/lib/postgresql/bring1970.csv' CSV HEADER;

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1980 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1980 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1980 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1980 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1980 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc;
) TO '/var/lib/postgresql/bring1980.csv' CSV HEADER;

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1990 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1990 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1990 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1990 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1990 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc;
) TO '/var/lib/postgresql/bring1990.csv' CSV HEADER;

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p2000 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p2000 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p2000 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p2000 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p2000 as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc;
) TO '/var/lib/postgresql/bring2000.csv' CSV HEADER;

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1820 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1820 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1820 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1820 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1820 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc;
) TO '/var/lib/postgresql/hold1820.csv' CSV HEADER;

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1830 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1830 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1830 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1830 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1830 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc;
) TO '/var/lib/postgresql/hold1830.csv' CSV HEADER;

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1840 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1840 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1840 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1840 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1840 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc;
) TO '/var/lib/postgresql/hold1840.csv' CSV HEADER;

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1850 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1850 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1850 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1850 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1850 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc;
) TO '/var/lib/postgresql/hold1850.csv' CSV HEADER;

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1860 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1860 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1860 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1860 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1860 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc;
) TO '/var/lib/postgresql/hold1860.csv' CSV HEADER;

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1870 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1870 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1870 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1870 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1870 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc;
) TO '/var/lib/postgresql/hold1870.csv' CSV HEADER;

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1880 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1880 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1880 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1880 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1880 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc;
) TO '/var/lib/postgresql/hold1880.csv' CSV HEADER;

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1890 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1890 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1890 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1890 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1890 as c, lexicon as l
where l.lemma like 'hold'
and c.w1 = l.wid
) a, lexicon b where