In [1]:
import pandas as pd

In [2]:
years = [1820, 1830, 1840, 1850, 1860, 1870, 1880, 1890, 1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000]
verbs = ['bear', 'bring', 'create', 'give', 'grant', 'hold', 'keep', 'lose', 'make', 'take','maintain', 'demand']

In [3]:
for v in verbs:
    for y in years:
        print(v + ' '+ str(y)+'algo')

bear 1820algo
bear 1830algo
bear 1840algo
bear 1850algo
bear 1860algo
bear 1870algo
bear 1880algo
bear 1890algo
bear 1900algo
bear 1910algo
bear 1920algo
bear 1930algo
bear 1940algo
bear 1950algo
bear 1960algo
bear 1970algo
bear 1980algo
bear 1990algo
bear 2000algo
bring 1820algo
bring 1830algo
bring 1840algo
bring 1850algo
bring 1860algo
bring 1870algo
bring 1880algo
bring 1890algo
bring 1900algo
bring 1910algo
bring 1920algo
bring 1930algo
bring 1940algo
bring 1950algo
bring 1960algo
bring 1970algo
bring 1980algo
bring 1990algo
bring 2000algo
create 1820algo
create 1830algo
create 1840algo
create 1850algo
create 1860algo
create 1870algo
create 1880algo
create 1890algo
create 1900algo
create 1910algo
create 1920algo
create 1930algo
create 1940algo
create 1950algo
create 1960algo
create 1970algo
create 1980algo
create 1990algo
create 2000algo
give 1820algo
give 1830algo
give 1840algo
give 1850algo
give 1860algo
give 1870algo
give 1880algo
give 1890algo
give 1900algo
give 1910algo
give 1920algo
give 1930algo
give 1940algo
give 1950algo
give 1960algo
give 1970algo
give 1980algo
give 1990algo
give 2000algo
grant 1820algo
grant 1830algo
grant 1840algo
grant 1850algo
grant 1860algo
grant 1870algo
grant 1880algo
grant 1890algo
grant 1900algo
grant 1910algo
grant 1920algo
grant 1930algo
grant 1940algo
grant 1950algo
grant 1960algo
grant 1970algo
grant 1980algo
grant 1990algo
grant 2000algo
hold 1820algo
hold 1830algo
hold 1840algo
hold 1850algo
hold 1860algo
hold 1870algo
hold 1880algo
hold 1890algo
hold 1900algo
hold 1910algo
hold 1920algo
hold 1930algo
hold 1940algo
hold 1950algo
hold 1960algo
hold 1970algo
hold 1980algo
hold 1990algo
hold 2000algo
keep 1820algo
keep 1830algo
keep 1840algo
keep 1850algo
keep 1860algo
keep 1870algo
keep 1880algo
keep 1890algo
keep 1900algo
keep 1910algo
keep 1920algo
keep 1930algo
keep 1940algo
keep 1950algo
keep 1960algo
keep 1970algo
keep 1980algo
keep 1990algo
keep 2000algo
lose 1820algo
lose 1830algo
lose 1840algo
lose 1850algo
lose 1860algo
lose 1870algo
lose 1880algo
lose 1890algo
lose 1900algo
lose 1910algo
lose 1920algo
lose 1930algo
lose 1940algo
lose 1950algo
lose 1960algo
lose 1970algo
lose 1980algo
lose 1990algo
lose 2000algo
make 1820algo
make 1830algo
make 1840algo
make 1850algo
make 1860algo
make 1870algo
make 1880algo
make 1890algo
make 1900algo
make 1910algo
make 1920algo
make 1930algo
make 1940algo
make 1950algo
make 1960algo
make 1970algo
make 1980algo
make 1990algo
make 2000algo
take 1820algo
take 1830algo
take 1840algo
take 1850algo
take 1860algo
take 1870algo
take 1880algo
take 1890algo
take 1900algo
take 1910algo
take 1920algo
take 1930algo
take 1940algo
take 1950algo
take 1960algo
take 1970algo
take 1980algo
take 1990algo
take 2000algo
maintain 1820algo
maintain 1830algo
maintain 1840algo
maintain 1850algo
maintain 1860algo
maintain 1870algo
maintain 1880algo
maintain 1890algo
maintain 1900algo
maintain 1910algo
maintain 1920algo
maintain 1930algo
maintain 1940algo
maintain 1950algo
maintain 1960algo
maintain 1970algo
maintain 1980algo
maintain 1990algo
maintain 2000algo
demand 1820algo
demand 1830algo
demand 1840algo
demand 1850algo
demand 1860algo
demand 1870algo
demand 1880algo
demand 1890algo
demand 1900algo
demand 1910algo
demand 1920algo
demand 1930algo
demand 1940algo
demand 1950algo
demand 1960algo
demand 1970algo
demand 1980algo
demand 1990algo
demand 2000algo

In [4]:
f = open("algoQueryPartitions.sql", "a+")
for v in verbs:
    for y in years:
        sqlQuery = """
COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM """ + 'p' + str(y) + "algo" + """ as c, lexicon as l
where l.lemma like '""" + v + """'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM """ + 'p' + str(y) + "algo" +""" as c, lexicon as l
where l.lemma like '""" + v + """'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM """ + 'p' + str(y) + "algo"+""" as c, lexicon as l
where l.lemma like '""" + v + """'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM """ + 'p' + str(y) + "algo"+ """ as c, lexicon as l
where l.lemma like '""" + v + """'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM """ + 'p' + str(y) + "algo" +""" as c, lexicon as l
where l.lemma like '""" + v + """'
and c.w1 = l.wid
) a, lexicon b where 
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO """ + "\'/var/lib/postgresql/algoResult/" + v + str(y) + ".csv\' CSV HEADER;\n"

        print(sqlQuery)
        f.write(sqlQuery)
f.close()

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1820algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1820algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1820algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1820algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1820algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1820.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1830algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1830algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1830algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1830algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1830algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1830.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1840algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1840algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1840algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1840algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1840algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1840.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1850algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1850algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1850algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1850algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1850algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1850.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1860algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1860algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1860algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1860algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1860algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1860.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1870algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1870algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1870algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1870algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1870algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1870.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1880algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1880algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1880algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1880algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1880algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1880.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1890algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1890algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1890algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1890algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1890algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1890.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1900algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1900algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1900algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1900algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1900algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1900.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1910algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1910algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1910algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1910algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1910algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1910.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1920algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1920algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1920algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1920algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1920algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1920.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1930algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1930algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1930algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1930algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1930algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1930.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1940algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1940algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1940algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1940algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1940algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1940.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1950algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1950algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1950algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1950algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1950algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1950.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1960algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1960algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1960algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1960algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1960algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1960.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1970algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1970algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1970algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1970algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1970algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1970.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1980algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1980algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1980algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1980algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1980algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1980.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1990algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1990algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1990algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1990algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1990algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear1990.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p2000algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p2000algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p2000algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p2000algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p2000algo as c, lexicon as l
where l.lemma like 'bear'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bear2000.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1820algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1820algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1820algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1820algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1820algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bring1820.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1830algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1830algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1830algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1830algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1830algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bring1830.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1840algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1840algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1840algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1840algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1840algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bring1840.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1850algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1850algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1850algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1850algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1850algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bring1850.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1860algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1860algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1860algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1860algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1860algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bring1860.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1870algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1870algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1870algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1870algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1870algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/algoResult/bring1870.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1880algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1880algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1880algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1880algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1880algo as c, lexicon as l
where l.lemma like 'bring'
and c.w1 = l.wid
) a, lexicon b where