In [1]:
import pandas as pd

In [2]:
years = [1820, 1830, 1840, 1850, 1860, 1870, 1880, 1890, 1900, 1910, 1920, 1930, 1940, 1950, 1960, 1970, 1980, 1990, 2000]
verbs = ['maintain', 'demand']

In [3]:
for v in verbs:
    for y in years:
        print(v + ' '+ str(y))

maintain 1820
maintain 1830
maintain 1840
maintain 1850
maintain 1860
maintain 1870
maintain 1880
maintain 1890
maintain 1900
maintain 1910
maintain 1920
maintain 1930
maintain 1940
maintain 1950
maintain 1960
maintain 1970
maintain 1980
maintain 1990
maintain 2000
demand 1820
demand 1830
demand 1840
demand 1850
demand 1860
demand 1870
demand 1880
demand 1890
demand 1900
demand 1910
demand 1920
demand 1930
demand 1940
demand 1950
demand 1960
demand 1970
demand 1980
demand 1990
demand 2000

In [4]:
f = open("queryPartitionsPart2.sql", "a+")
for v in verbs:
    for y in years:
        sqlQuery = """
COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM """ + 'p' + str(y) + """ as c, lexicon as l
where l.lemma like '""" + v + """'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM """ + 'p' + str(y) + """ as c, lexicon as l
where l.lemma like '""" + v + """'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM """ + 'p' + str(y) + """ as c, lexicon as l
where l.lemma like '""" + v + """'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM """ + 'p' + str(y) + """ as c, lexicon as l
where l.lemma like '""" + v + """'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM """ + 'p' + str(y) + """ as c, lexicon as l
where l.lemma like '""" + v + """'
and c.w1 = l.wid
) a, lexicon b where 
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO """ + "\'/var/lib/postgresql/" + v + str(y) + ".csv\' CSV HEADER;\n"

        print(sqlQuery)
        f.write(sqlQuery)
f.close()

COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1820 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1820 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1820 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1820 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1820 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/maintain1820.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1830 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1830 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1830 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1830 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1830 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/maintain1830.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1840 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1840 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1840 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1840 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1840 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/maintain1840.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1850 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1850 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1850 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1850 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1850 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/maintain1850.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1860 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1860 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1860 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1860 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1860 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/maintain1860.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1870 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1870 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1870 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1870 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1870 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/maintain1870.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1880 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1880 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1880 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1880 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1880 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/maintain1880.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1890 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1890 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1890 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1890 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1890 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/maintain1890.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1900 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1900 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1900 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1900 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1900 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/maintain1900.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1910 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1910 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1910 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1910 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1910 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/maintain1910.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1920 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1920 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1920 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1920 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1920 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/maintain1920.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1930 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1930 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1930 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1930 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1930 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/maintain1930.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1940 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1940 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1940 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1940 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1940 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/maintain1940.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1950 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1950 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1950 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1950 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1950 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/maintain1950.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1960 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1960 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1960 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1960 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1960 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/maintain1960.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1970 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1970 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1970 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1970 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1970 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/maintain1970.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1980 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1980 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1980 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1980 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1980 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/maintain1980.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1990 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1990 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1990 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1990 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1990 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/maintain1990.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p2000 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p2000 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p2000 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p2000 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p2000 as c, lexicon as l
where l.lemma like 'maintain'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/maintain2000.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1820 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1820 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1820 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1820 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1820 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/demand1820.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1830 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1830 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1830 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1830 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1830 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/demand1830.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1840 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1840 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1840 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1840 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1840 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/demand1840.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1850 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1850 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1850 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1850 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1850 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/demand1850.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1860 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1860 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1860 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1860 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1860 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/demand1860.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1870 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1870 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1870 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1870 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1870 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/demand1870.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1880 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL
SELECT c.w3 FROM p1880 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL
SELECT c.w4 FROM p1880 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL
SELECT c.w5 FROM p1880 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL
SELECT c.w6 FROM p1880 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
) a, lexicon b where
( b.pos like '%nn@%' or b.pos like '%nn\%%' or b.pos like 'nn' or b.pos like '%nn1%' or b.pos like '%nn2%')
and a.w2 = b.wid group by b.lemma order by count(*) desc
) TO '/var/lib/postgresql/demand1880.csv' CSV HEADER;


COPY (
SELECT lemma, count(*) from (
SELECT c.w2 FROM p1890 as c, lexicon as l
where l.lemma like 'demand'
and c.w1 = l.wid
UNION ALL